// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs edit-flowchart`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "draw-flowchart",
    "icon": "🖍️",
    "name": {
      "en": "Draw Flowchart",
      "ja": "フローチャート作成",
      "zh": "绘制流程图",
      "de": "Flussdiagramm zeichnen",
      "es": "Dibujar diagrama de flujo"
    },
    "desc": {
      "en": "Write flowchart syntax, see it rendered live. Export as SVG or PNG.",
      "ja": "フローチャート記法を書くとその場でプレビュー。SVG/PNGで書き出し。",
      "zh": "输入流程图语法即时预览，导出为 SVG 或 PNG。",
      "de": "Flussdiagramm-Syntax schreiben und live sehen. Export als SVG oder PNG.",
      "es": "Escribe la sintaxis del diagrama y visualízalo al instante. Exporta como SVG o PNG."
    }
  },
  {
    "slug": "edit-ascii-diagram",
    "icon": "🧱",
    "name": {
      "en": "Edit ASCII Diagram",
      "ja": "罫線図エディタ",
      "zh": "编辑框线图",
      "de": "ASCII-Diagramm bearbeiten",
      "es": "Editar diagrama ASCII"
    },
    "desc": {
      "en": "Edit a Unicode box-drawing diagram — CJK and emoji widths stay correctly aligned.",
      "ja": "Unicode罫線図をGUIで編集。全角文字・絵文字の幅もズレずに整列。",
      "zh": "编辑 Unicode 框线图，中日韩字符与表情符号宽度始终正确对齐。",
      "de": "Bearbeite ein Unicode-Kasten-Diagramm — CJK- und Emoji-Breiten bleiben korrekt ausgerichtet.",
      "es": "Edita un diagrama de cajas Unicode — los anchos CJK y emoji se mantienen correctamente alineados."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'edit-flowchart';
